### ISSUE TITLE
Possible fix for lauching newest chrome on Wine

### ISSUE THREAD

**Issue by MagicD3VIL** [nxjosephofficial/primevideo-linux#3]
Greetings,
Amazon Prime Video seems to now require the newest Chrome 100. I've seen that you mentioned that you couldn't launch the newest Google Chrome on Wine. For me, the solution was to add `--no-sandbox` as the starting parameter after `chrome.exe`.

Feel free to try it out for yourself and update the guide accordingly if it works for you :)

Cheers

**Comment by nxjosephofficial** [comment]
Hi. Thank you.

Actually we can watch primevideo with older version but we have to update the Widevine component in chrome://components .
I launched Chrome v100 with your solution, it worked.
There is a warning because we are using --no-sandbox parameter.
![rNoWQVal](https://user-images.githubusercontent.com/61632416/165331337-9363fb81-fda3-42af-a6ab-0b8b87d07408.jpg)

You can look to closed issue for how to update Widevine component.

**Comment by nxjosephofficial** [comment]
I updated the guide for how to update Widevine component for solving require newest chrome alert.
